---
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: ubuntu
    image: docker.io/geerlingguy/docker-ubuntu2404-ansible
    pre_build_image: true
#  - name: centos
#    image: docker.io/oraclelinux:8
#    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible